### PR TITLE
Add https support (lts-incremental)

### PR DESCRIPTION
**Pull request by ChrisBoehmCA**
Port changes from master to lts-incremental to support https

### CODE REVIEW

**Comment by matthewpwilson** [comment]
I'm keen to see this merged, we need it order to use lts-incremental as a dependency.

**Comment by ChrisBoehmCA** [comment]
Whoops, looks like we forgot about this one. @zFernand0  should be able to review and merge when he comes back on Monday

**Comment by matthewpwilson** [comment]
@zFernand0 any outlook on this please?

**Comment by zFernand0** [comment]
> @zFernand0 any outlook on this please?

I will upen a PR to get this issues resolved. then we can update the branch :)
Sorry for the wait.

**Comment by matthewpwilson** [comment]
Thanks very much.

**Pull request merged**
