### PR TITLE
Shrinkwrap + Node:16.13.1 on Jenkinsfile + NPM:8 on GHA

### PR DESCRIPTION
**Pull request by zFernand0**

### CODE REVIEW

**Comment by zFernand0** [comment]
No more changes planned

**Comment by gejohnston** [comment]
Have we determined what best practices should be when a developer updates direct dependencies?

- Use `npm outdated` ?
- Manually edit package.json
- Use `npm update` ?
- Rerun `npm install` ?
- What options might be best for `npm shrinkwrap` ?

If we have recommendations, maybe we should place such text into the README files of
each repository under the "Building from source" section, or maybe a new section?

**Comment by zFernand0** [comment]
> Have we determined what best practices should be when a developer updates direct dependencies?
> 
> * Use `npm outdated` ?
> * Manually edit package.json
> * Use `npm update` ?
> * Rerun `npm install` ?
> * What options might be best for `npm shrinkwrap` ?
> 
> If we have recommendations, maybe we should place such text into the README files of each repository under the "Building from source" section, or maybe a new section?

I don't think we've made a decision on how to update dependencies within npm-shrinkwrap.

Personally, I do like the top-level summary provided by `npm outdated` even though it may not always work great with prerelease strings (i.e. unexpected `latest` suggestion) and kind of mixes regular dependencies with dev Dependencies.
However, `npm outdated` seems to only provide the information and we have to make the decision. 

The case of `npm update` should work for transitive dependencies based on their restrictions (`~`, `^`, ...).

I do believe that between `npm audit fix` and `npm update` we should be covered in terms of regularly updating the dependencies. These two scripts could be executed right before every Zowe code freeze.

Either way, I think we should update the README files once we decide on cadence and process 😋

**Review by gejohnston — APPROVED** [review]
I imagine that most of the other shrinkwrap PRs will be similar to this one. Since I have no request for change on this PR, I probably will not have any on the others, so I wanted to say thanks for moving through so many repos so quickly.

**Review by awharn — APPROVED** [review]

**Pull request merged**
